### ISSUE TITLE
Review builds for unwanted jars

### ISSUE THREAD

**Issue by etj** [GeoNode/geoserver-geonode-ext#148]
This happened with a GeoServer 2.19.7:
```
 java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/geoserver] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
```
causing a bootloop.

<details>
  <summary>TL;DR; Full stacktrace</summary>
  
```
03-Mar-2023 09:27:04.647 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/apache-tomcat-9.0.31/web
apps/geoserver.war]
03-Mar-2023 09:27:08.332 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/opt/apache-tomcat-9.
0.31/webapps/geoserver.war]
        java.lang.IllegalStateException: Error starting child
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
        Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
                ... 37 more
        Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/geoserver] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.bouncycastle.asn1.ASN1EncodableVector->org.bouncycastle.asn1.DEREncodableVector->org.bouncycastle.asn1.ASN1EncodableVector]
                at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2186)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2124)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2070)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:2040)
                at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1993)
                at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1243)
                at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1142)
                at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:774)
                at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:301)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5051)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                ... 38 more
```
</details>

It turned out we have a bit too many bouncycastle jars, so a race condition popped up when the wrong jar got loaded first; here some involved jars:
```
geoserver-geonode-ext/geoserver/web-app$ ll target/geoserver/WEB-INF/lib/bc*
-rw-rw-r-- 1 geosol geosol  192035 feb  6 20:01 target/geoserver/WEB-INF/lib/bcmail-jdk14-138.jar
-rw-rw-r-- 1 geosol geosol   93894 feb  6 20:01 target/geoserver/WEB-INF/lib/bcmail-jdk14-1.64.jar
-rw-rw-r-- 1 geosol geosol  738270 feb  6 20:01 target/geoserver/WEB-INF/lib/bcpkix-jdk14-1.64.jar
-rw-rw-r-- 1 geosol geosol 1551468 feb  6 20:01 target/geoserver/WEB-INF/lib/bcprov-jdk14-138.jar
-rw-rw-r-- 1 geosol geosol 4189874 feb 10 16:51 target/geoserver/WEB-INF/lib/bcprov-jdk15on-1.60.jar
-rw-rw-r-- 1 geosol geosol   39985 feb  6 20:01 target/geoserver/WEB-INF/lib/bctsp-jdk14-1.46.jar
```
As a first try, `bcprov-jdk14-138.jar` was removed, and this made GeoServer boot properly.

`mvn dependency:tree` reports these dependencies:
```
[INFO] +- org.xhtmlrenderer:flying-saucer-pdf:jar:9.1.20:compile
[INFO] |  +- org.bouncycastle:bcmail-jdk14:jar:1.64:compile
[INFO] |  |  \- org.bouncycastle:bcpkix-jdk14:jar:1.64:compile
[INFO] |  \- org.bouncycastle:bctsp-jdk14:jar:1.46:compile
[INFO] +- com.lowagie:itext:jar:2.1.5:compile
[INFO] |  +- bouncycastle:bcmail-jdk14:jar:138:compile
[INFO] |  \- bouncycastle:bcprov-jdk14:jar:138:compile
```

The only other bouncycastle dep, that is `org.bouncycastle:bcprov-jdk15on:jar:1.60:compile` is imported by `gs-web-core`.

in this project we have:
```xml
        <dependency>
          <groupId>org.xhtmlrenderer</groupId>
          <artifactId>flying-saucer-core</artifactId>
          <version>9.1.20</version>
          <exclusions>
            <exclusion>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk14</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
        <dependency>
          <groupId>org.xhtmlrenderer</groupId>
          <artifactId>flying-saucer-pdf</artifactId>
          <version>9.1.20</version>
          <exclusions>
            <exclusion>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk14</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
        <dependency>
            <groupId>com.lowagie</groupId>
            <artifactId>itext</artifactId>
            <version>2.1.5</version>
        </dependency>
```
so the `bcprov-jdk14` is already excluded from the xhtmlrenderer, but not from itext.

- [ ] exclude bcprov-jdk14 from itext
- [ ] rebuild and re-deploy the artifact
- [ ] investigate to find out if the added dependecies are really needed
- [ ] perform this check on the various deployed versions

**Comment by giohappy** [comment]
@etj we're not supporting 2.19 in GeoNode anymore, and I don't see this happening neither with 2.20.7 (GN 4.0.3) nor with 2.23.1.
Do you think it's still worth an investigation?

**Comment by etj** [comment]
@giohappy we released new war versions that may break because of this race condition, that's it

**Comment by giohappy** [comment]
@afabiani can you please take a look at this?

**Comment by afabiani** [comment]
that should be done already from 2.20.7+

**Comment by giohappy** [comment]
>that should be done already from 2.20.7+

@afabiani could you confirm the supposition?

**Comment by afabiani** [comment]
![image](https://user-images.githubusercontent.com/1278021/229181788-10d4f7dc-b2ff-4eb7-af50-981cbb08368f.png)

confirmed
