### ISSUE TITLE
Remove gs-notification module

### ISSUE THREAD

**Issue by etj** [GeoNode/geoserver-geonode-ext#81]
The notification module is not used and may lead to runtime NPE.

https://github.com/GeoNode/geoserver-geonode-ext/blob/2.18.3/geoserver/pom.xml#L534-L549

To be removed on
- [ ] 3.2.x
- (any other branch?)

**Comment by etj** [comment]
2021-06-03 13:01:33,820 INFO [org.geoserver.flow] - Request control-flow performed, running requests: 1, blocked requests: 0
2021-06-03 13:01:33,820 DEBUG [org.geoserver.geofence] - Admin level access, not applying default style for this request
2021-06-03 13:01:33,824 DEBUG [org.geoserver.wfs] - Locating FeatureSource uri:'http://iter_cultura_ws.local' name:'cultura_patrimonio_geometry'
2021-06-03 13:01:33,826 DEBUG [org.geoserver.jdbcconfig.internal] - Original filter: [Filter.INCLUDE AND [ prefix = http://iter_cultura_ws.local ]]
2021-06-03 13:01:33,826 DEBUG [org.geoserver.jdbcconfig.internal] - Supported filter: [ prefix = http://iter_cultura_ws.local ]
2021-06-03 13:01:33,826 DEBUG [org.geoserver.jdbcconfig.internal] - Unsupported filter: Filter.INCLUDE
2021-06-03 13:01:33,826 DEBUG [org.geoserver.jdbcconfig.internal] - select id from object where type_id in (2) AND (
oid IN (SELECT oid FROM object_property WHERE property_type IN (7) AND value = 'http://iter_cultura_ws.local') /* [ prefix = http://iter_cultura_ws.local ] */
)
 ORDER BY oid
2021-06-03 13:01:33,829 DEBUG [org.geoserver.jdbcconfig.internal] - query returned 0 records in 3.009 ms
2021-06-03 13:01:33,840 DEBUG [org.geoserver.geofence] - Getting access limits for Resource cultura_patrimonio_geometry
2021-06-03 13:01:33,840 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for layer cultura_patrimonio_geometry
2021-06-03 13:01:33,840 DEBUG [org.geoserver.geofence] - Returning mode HIDE for resource FeatureTypeInfoImpl[cultura_patrimonio_geometry]
2021-06-03 13:01:33,840 DEBUG [org.geoserver.geofence] - Getting access limits for workspace iter_cultura_ws
2021-06-03 13:01:33,840 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for workspace iter_cultura_ws
2021-06-03 13:01:33,847 DEBUG [org.geoserver.jdbcconfig.internal] - SELECT ID FROM DEFAULT_OBJECT WHERE DEF_KEY = 'NamespaceInfo'
2021-06-03 13:01:33,867 DEBUG [org.geoserver.wfs] - located FeatureType w/ typeRef 'iter_cultura_ds:cultura_patrimonio_geometry' and elementName '{http://iter_cultura_ws.local}cultura_patrimonio_geometry'
2021-06-03 13:01:33,878 DEBUG [org.geoserver.wfs] - Transaction Insert:org.geoserver.wfs.request.Insert$WFS20@66053eae
2021-06-03 13:01:33,880 DEBUG [org.geoserver.wfs] - Use featureValidation to check contents of insert
2021-06-03 13:01:33,880 INFO [org.geoserver.gwc] - DataStoreChange: {http://iter_cultura_ws.local}cultura_patrimonio_geometry TransactionEventType[PreInsert]
2021-06-03 13:01:33,883 DEBUG [org.geoserver.geofence] - Getting access limits for workspace iter_cultura_ws
2021-06-03 13:01:33,883 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for workspace iter_cultura_ws
2021-06-03 13:01:33,887 DEBUG [org.geoserver.geofence] - Getting access limits for Resource cultura_patrimonio_geometry
2021-06-03 13:01:33,888 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for layer cultura_patrimonio_geometry
2021-06-03 13:01:33,888 DEBUG [org.geoserver.geofence] - Returning mode HIDE for resource FeatureTypeInfoImpl[cultura_patrimonio_geometry]
2021-06-03 13:01:33,888 DEBUG [org.geoserver.geofence] - Getting access limits for workspace iter_cultura_ws
2021-06-03 13:01:33,888 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for workspace iter_cultura_ws
2021-06-03 13:01:33,889 DEBUG [org.geoserver.jdbcconfig.internal] - Original filter: [ resource.id = FeatureTypeInfo.cb403fe4-e234-46c8-b782-7a749cdd7bac ]
2021-06-03 13:01:33,889 DEBUG [org.geoserver.jdbcconfig.internal] - Supported filter: [ resource.id = FeatureTypeInfo.cb403fe4-e234-46c8-b782-7a749cdd7bac ]
2021-06-03 13:01:33,889 DEBUG [org.geoserver.jdbcconfig.internal] - Unsupported filter: Filter.INCLUDE
2021-06-03 13:01:33,889 DEBUG [org.geoserver.jdbcconfig.internal] - select id from object where type_id in (14) AND (
oid IN (SELECT oid FROM object_property WHERE property_type IN (256) AND value = 'FeatureTypeInfo.cb403fe4-e234-46c8-b782-7a749cdd7bac') /* [ resource.id = FeatureTypeInfo.cb403fe4-e234-46c8-b782-7a749cdd7bac ] */
)
 ORDER BY oid
2021-06-03 13:01:33,891 DEBUG [org.geoserver.jdbcconfig.internal] - query returned 1 records in 1.571 ms
2021-06-03 13:01:33,893 DEBUG [org.geoserver.jdbcconfig.internal] - select blob from object where id = 'LayerInfo.1451ef6e-a9bf-4169-a6bc-8f9b84516fde'
2021-06-03 13:01:33,895 DEBUG [org.geoserver.jdbcconfig.internal] - select blob from object where id = 'StyleInfoImpl-37b18cc6:14d5d036d48:-8000'
2021-06-03 13:01:33,899 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for layer cultura_patrimonio_geometry
2021-06-03 13:01:33,899 DEBUG [org.geoserver.geofence] - Returning mode HIDE for resource FeatureTypeInfoImpl[cultura_patrimonio_geometry]
2021-06-03 13:01:33,899 DEBUG [org.geoserver.geofence] - Getting access limits for workspace iter_cultura_ws
2021-06-03 13:01:33,899 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for workspace iter_cultura_ws
2021-06-03 13:01:33,900 DEBUG [org.geoserver.jdbcconfig.internal] - Original filter: [[ layers.id = LayerInfo.1451ef6e-a9bf-4169-a6bc-8f9b84516fde ] OR [ rootLayer.id equals LayerInfo.1451ef6e-a9bf-4169-a6bc-8f9b84516fde ]]
2021-06-03 13:01:33,900 DEBUG [org.geoserver.jdbcconfig.internal] - Supported filter: Filter.INCLUDE
2021-06-03 13:01:33,900 DEBUG [org.geoserver.jdbcconfig.internal] - Unsupported filter: [[ layers.id = LayerInfo.1451ef6e-a9bf-4169-a6bc-8f9b84516fde ] OR [ rootLayer.id equals LayerInfo.1451ef6e-a9bf-4169-a6bc-8f9b84516fde ]]
2021-06-03 13:01:33,900 DEBUG [org.geoserver.jdbcconfig.internal] - select id from object where type_id in (15) AND (
(1=1) /* INCLUDE */
)
 ORDER BY oid
2021-06-03 13:01:33,902 DEBUG [org.geoserver.jdbcconfig.internal] - query returned 0 records in 1.180 ms
2021-06-03 13:01:33,908 DEBUG [org.geoserver.jdbcconfig.internal] - Original filter: [Filter.INCLUDE AND [ prefix = http://iter_cultura_ws.local ]]
2021-06-03 13:01:33,908 DEBUG [org.geoserver.jdbcconfig.internal] - Supported filter: [ prefix = http://iter_cultura_ws.local ]
2021-06-03 13:01:33,908 DEBUG [org.geoserver.jdbcconfig.internal] - Unsupported filter: Filter.INCLUDE
2021-06-03 13:01:33,908 DEBUG [org.geoserver.jdbcconfig.internal] - select id from object where type_id in (2) AND (
oid IN (SELECT oid FROM object_property WHERE property_type IN (7) AND value = 'http://iter_cultura_ws.local') /* [ prefix = http://iter_cultura_ws.local ] */
)
 ORDER BY oid
2021-06-03 13:01:33,909 DEBUG [org.geoserver.jdbcconfig.internal] - query returned 0 records in 1.383 ms
2021-06-03 13:01:33,918 DEBUG [org.geoserver.geofence] - Getting access limits for Resource cultura_patrimonio_geometry
2021-06-03 13:01:33,918 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for layer cultura_patrimonio_geometry
2021-06-03 13:01:33,918 DEBUG [org.geoserver.geofence] - Returning mode HIDE for resource FeatureTypeInfoImpl[cultura_patrimonio_geometry]
2021-06-03 13:01:33,918 DEBUG [org.geoserver.geofence] - Getting access limits for workspace iter_cultura_ws
2021-06-03 13:01:33,918 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for workspace iter_cultura_ws
2021-06-03 13:01:33,926 INFO [org.geoserver.gwc] - DataStoreChange: {http://iter_cultura_ws.local}cultura_patrimonio_geometry TransactionEventType[PostInsert]
2021-06-03 13:01:33,931 DEBUG [org.geoserver.jdbcconfig.internal] - Original filter: [Filter.INCLUDE AND [ prefix = http://iter_cultura_ws.local ]]
2021-06-03 13:01:33,931 DEBUG [org.geoserver.jdbcconfig.internal] - Supported filter: [ prefix = http://iter_cultura_ws.local ]
2021-06-03 13:01:33,931 DEBUG [org.geoserver.jdbcconfig.internal] - Unsupported filter: Filter.INCLUDE
2021-06-03 13:01:33,931 DEBUG [org.geoserver.jdbcconfig.internal] - select id from object where type_id in (2) AND (
oid IN (SELECT oid FROM object_property WHERE property_type IN (7) AND value = 'http://iter_cultura_ws.local') /* [ prefix = http://iter_cultura_ws.local ] */
)
 ORDER BY oid
2021-06-03 13:01:33,932 DEBUG [org.geoserver.jdbcconfig.internal] - query returned 0 records in 1.129 ms
2021-06-03 13:01:33,935 DEBUG [org.geoserver.geofence] - Getting access limits for Resource cultura_patrimonio_geometry
2021-06-03 13:01:33,935 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for layer cultura_patrimonio_geometry
2021-06-03 13:01:33,935 DEBUG [org.geoserver.geofence] - Returning mode HIDE for resource FeatureTypeInfoImpl[cultura_patrimonio_geometry]
2021-06-03 13:01:33,935 DEBUG [org.geoserver.geofence] - Getting access limits for workspace iter_cultura_ws
2021-06-03 13:01:33,935 DEBUG [org.geoserver.geofence] - Admin level access, returning full rights for workspace iter_cultura_ws
2021-06-03 13:01:33,940 INFO [org.geoserver.gwc.layer] - No GWC GridSet named 'EPSG:3857' exists.
2021-06-03 13:01:33,940 DEBUG [org.geoserver.gwc] - Requested truncation bounds do not intersect cached layer bounds, ignoring truncate request
2021-06-03 13:01:33,940 DEBUG [org.geoserver.gwc] - Requested truncation bounds do not intersect cached layer bounds, ignoring truncate request
ERROR [org.geoserver.ows] -
org.geoserver.wfs.WFSException: java.lang.NullPointerException
        at org.geoserver.wfs.Transaction.transaction(Transaction.java:99)
        at org.geoserver.wfs.DefaultWebFeatureService20.transaction(DefaultWebFeatureService20.java:180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:50)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy170.transaction(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:877)
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:265)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
        at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:70)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
        at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:142)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
        at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
        at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:172)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.geoserver.notification.NotificationListener.notify(NotificationListener.java:19)
        at org.geoserver.notification.NotificationTransactionListener.afterTransaction(NotificationTransactionListener.java:77)
        at org.geoserver.wfs.Transaction.fireAfterTransaction(Transaction.java:435)
        at org.geoserver.wfs.Transaction.execute(Transaction.java:369)
        at org.geoserver.wfs.Transaction.transaction(Transaction.java:93)
        ... 117 more
2021-06-03 13:01:34,064 INFO [org.geoserver.flow] - releasing flow controllers for [WFS 2.0.0 Transaction]
2021-06-03 13:01:34,064 INFO [org.geoserver.flow] - Request completed, running requests: 0, blocked requests: 0
2021-06-03 13:01:34,066 DEBUG [org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1] - SecurityContextHolder now cleared, as request processing completed
2021-06-03 13:01:40,090 DEBUG [org.geoserver.wps.jdbc] - removing statuses matching [[[ NOT [ completionTime IS NULL ] ] AND [ completionTime Before 2021-06-03T12:41Z ]] AND [[ NOT [ lastUpdated IS NULL ] ] AND [ lastUpdated Before 2021-06-03T12:41Z ]]]
2021-06-03 13:01:40,091 WARN [org.geotools.jdbc] - Error occurred closing connection
2021-06-03 13:01:40,091 WARN [org.geoserver.wcs.response] - Error occurred while trying to clean up old coverages from temp storage
org.geoserver.wps.WPSException: Failure to remove status by filter: [[[ NOT [ completionTime IS NULL ] ] AND [ completionTime Before 2021-06-03T12:41Z ]] AND [[ NOT [ lastUpdated IS NULL ] ] AND [ lastUpdated Before 2021-06-03T12:41Z ]]]
        at org.geoserver.wps.jdbc.JDBCStatusStore.remove(JDBCStatusStore.java:316)
        at org.geoserver.wps.executor.ProcessStatusTracker.cleanExpiredStatuses(ProcessStatusTracker.java:135)
        at org.geoserver.wps.WPSStorageCleaner.run(WPSStorageCleaner.java:47)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException
        at org.geotools.data.store.ContentFeatureCollection.size(ContentFeatureCollection.java:248)
        at org.geoserver.wps.jdbc.JDBCStatusStore.remove(JDBCStatusStore.java:307)
        ... 10 more
Caused by: java.io.IOException
        at org.geotools.jdbc.JDBCDataStore.getAggregateValue(JDBCDataStore.java:1485)
        at org.geotools.jdbc.JDBCDataStore.getCount(JDBCDataStore.java:1379)
        at org.geotools.jdbc.JDBCFeatureSource.getCountInternal(JDBCFeatureSource.java:444)
        at org.geotools.data.store.ContentFeatureSource.getCount(ContentFeatureSource.java:473)
        at org.geotools.jdbc.JDBCFeatureStore.getCountInternal(JDBCFeatureStore.java:176)
        at org.geotools.data.store.ContentFeatureSource.getCount(ContentFeatureSource.java:473)
        at org.geotools.data.store.ContentFeatureCollection.size(ContentFeatureCollection.java:225)
        ... 11 more
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:350)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
        at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.geotools.jdbc.JDBCDataStore.getAggregateValue(JDBCDataStore.java:1452)
        ... 17 more
Caused by: java.io.EOFException
        at org.postgresql.core.PGStream.receiveChar(PGStream.java:443)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2057)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        ... 26 more

**Comment by giohappy** [comment]
@etj I guess we can close this, right?
